language: csharp
mono: none
dotnet: 1.0.1
install:
  - dotnet restore Grace.sln
script:
- dotnet test -f netcoreapp1.0 tests/Grace.DependencyInjection.Extensions.Tests/Grace.DependencyInjection.Extensions.Tests.csproj

